dataset_name: mri-radar
train_split: ['training']
val_split: ['validation']
dataset: {
  json_file: ./data/mri/annotations/mri_split2.json,
  feat_folder: ./data/mri/pose_features,
  file_prefix: ~,
  file_ext: .npz,
  num_classes: 10,
  input_dim: 51,
  feat_stride: 1,
  num_frames: 1,
  default_fps: 50,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  downsample_rate: 25,
  max_seq_len: 2304,
}
model: {
  embd_dim: 192,
  fpn_dim: 192,
  head_dim: 192,
  backbone_arch: [2, 2, 5],
  regression_range: [
    [0, 0.00001], [0, 0.00001], [0, 0.00001],
    [0, 0.00001], [0, 0.00001], [0, 10000]
  ],
  fpn_type: identity,
  max_buffer_len_factor: 2.0,
  n_mha_win_size: 19,
  use_rel_pe: True,
}
opt: {
  learning_rate: 0.0001,
  warmup_epochs: 20,
  epochs: 100,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  duration_thresh: 1.0,
  pre_nms_topk: 1000,
  max_seg_num: 200,
  min_score: 0.001,
  nms_sigma : 0.75,
  multiclass_nms: True
}
output_folder: ./ckpt/
